

source('fog/get_fog.R', echo=TRUE)
source('fog/get_fog_speaker_data.R', echo=TRUE)
source('fog/get_within_call_data.R', echo=TRUE)
source('fog/get_fog_by_half.R', echo=TRUE)
# source('fog/get_lm_tone_words.R', echo=TRUE)
source('fog/get_tone_data.R', echo=TRUE)
source('fog/get_sent_count.R', echo=TRUE)
source('fog/get_fl_data.R', echo=TRUE)
source('fog/get_long_words.R', echo=TRUE)
source('fog/create_word_freq.R', echo=TRUE)
source('fog/create_sics.R', echo=TRUE)
source('fog/create_jargon_words.R', echo=TRUE)
source("fog/cast_fog_data.R", echo = TRUE)
source("fog/create_fog_data.R", echo = TRUE)
