source("fog/get_nchars.R")
source("fog/get_other_measures.R")
system("psql < fog/word_freq.sql")
system("psql < fog/num_jargon_words.sql")
system("psql < pl_functions/sent_count.sql")
source('fog/get_fog_speaker_data.R')
source('fog/get_within_call_data.R')
source('fog/get_fog_by_half.R')
source('fog/cast_fog_data.R', echo=TRUE)
